### ISSUE TITLE
241122 HTML&CSS로 프로필 만들기

### ISSUE THREAD

**Issue by sinhye-design** [sinhye-design/deepdive-code-study#1]
### 진행사항

HTML과 CSS를 활용해서 만든 기본 프로필은 업로드 및 연동완료하였습니다.
심화 버전을 만들기 위해 피그마에서 디자인을 하는 중입니다.

### 배운 점

1. vscode - git hub 커밋하고 연동시 소스제어 무한로딩이 일어났을때, 커밋 메시지를 작성함으로써 해결함
2. 폴더명과 파일명을 영문 소문자로 작성하자
3. image파일명도 영문으로 작성하자
4. 연동안됨 이슈가 일어난다면 폴더를 이사해보고 폴더명도 바꿔보고 요리조리 시도해보자

**Comment by sinhye-design** [comment]
-중간 코멘트
근데 오늘 안에 디자인하고(컴포넌트 만들고)
CSS작업까지 다 못 할듯 합니다요...ㅜㅜ

**Comment by sinhye-design** [comment]
### 배운 점

1. vscode - git hub 커밋하고 연동시 소스제어 무한로딩이 일어났을때, 커밋 메시지를 작성함으로써 해결함
2. 폴더명과 파일명을 영문 소문자로 작성하자
3. image파일명도 영문으로 작성하자
4. 연동안됨 이슈가 일어난다면 폴더를 이사해보고 폴더명도 바꿔보고 요리조리 시도해보자

**Comment by sinhye-design** [comment]
### 디렉토리 작성

https://sinhye-design.github.io/deepdive-code-study/241122/html/profile.html

**Comment by RunaUXLabs** [comment]
잘했어요!
css를 아는 사람만 오른쪽 도전하라고 한거지, 모두 하라고 한 건 아니었어요 ㅎㅎ
다음주 월요일에 css 구조 설명하면서 프로필 뜯어보기 할거예요!
너무 걱정말고 차근차근 넘어오자구요😉

**Comment by sinhye-design** [comment]
확인 감사합니다!
지금 디자인한 파일을 바탕으로 CSS 적용해보고 있습니다!

**Comment by sinhye-design** [comment]
### 추가 작업 - 프로필 심화 버전

https://sinhye-design.github.io/deepdive-code-study/241122/html/profile2.html

**MEMO**
디자인한 파일을 바탕으로 직접 CSS를 적용해보았는데요.
야근을 해서 조금 더 작업을 했으나 왼쪽 섹션하다가 지쳐서 여기까지만 하겠습니다..
다음주에 더 열심히 배워서 오른쪽도 기깔나게 만들어보는 걸로~!
